# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3901f2bf74bff962496bb360f04c8f79da61020ce7ed7a98b4867aeec657a40639f0516bb73ecd81b33592e4b91cc50af05811fcbcec85429d293571a347c57e

test:
  secret_key_base: 43fb4750fbbf621d04b57469e85fee9c4b7a0076df4ebf266da88e1ee5b013e6a781d88228034451d96bfe1613ba664199586999ff56b65f93decfaebc29ca9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
